apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-nodeapp
  labels:
    app: app-uthv2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-uthv2
  template:
    metadata:
      labels:
        app: app-uthv2
    spec:
      containers:
      - name: nodeserver
        image: uthdockerhub/app-uthv2:latest
        ports:
        - containerPort: 3000