apiVersion: v1
kind: Service
metadata:
  name: service-nodeapp
spec:
  selector:
    app: app-uthv2
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 31110